### ISSUE TITLE
Add custom port for Dask dashboard

### ISSUE THREAD

**Issue by genomewalker** [ChristianMichelsen/metadamage#6]
Hi Christian
would it be possible to have an option to change the `dashboard_address` [here](https://github.com/ChristianMichelsen/metadamage/blob/d62ab522cf8f308bcb35bb5695d5ccaa2a6ae483/metadamage/counts.py#L222). It clashes with other apps that use the default `8787` port.

Thanks
Antonio

**Comment by ChristianMichelsen** [comment]
Of course, I'll add it as soon as I have some extra time!

**Comment by ChristianMichelsen** [comment]
I have now added `--dask-port` to `metadamage fit` (along with `--dashboard-port` and `--dashboard-host` to `metadamage dashboard`) in version 0.4.3. Does this fix the problem?
