### ISSUE TITLE
conda installation guide fails on geogenetics cluster due to missing jaxlib==0.1.56

### ISSUE THREAD

**Issue by vincentvendius** [ChristianMichelsen/metadamage#7]
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.56 (from numpyro) (from versions: 0.1.60, 0.1.61, 0.1.62, 0.1.63, 0.1.64, 0.1.65, 0.1.66, 0.1.67, 0.1.68, 0.1.69, 0.1.70, 0.1.71, 0.1.72, 0.1.73)
ERROR: No matching distribution found for jaxlib==0.1.56

failed

CondaEnvException: Pip failed

**Comment by ChristianMichelsen** [comment]
Hi @vincentvendius!

This is the old version of metadamage. I should probably make this repo private again so that people do not find it by accident. The new version, metaDMG, is not really public yet, but you can still find it on PyPi ;)
